// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credentials.sql

package sqlite

import (
	"context"
	"database/sql"
)

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM provider_credentials
WHERE id = ?
`

func (q *Queries) DeleteCredential(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCredential, id)
	return err
}

const getLatestCredential = `-- name: GetLatestCredential :one
SELECT id, provider_id, kind, ciphertext, nonce, key_ref, cipher,
       hint, account_email, status, issued_at, expires_at, expiry_is_estimate,
       last_verified_at, last_verify_error, created_at, updated_at
FROM provider_credentials
WHERE provider_id = ?
  AND kind = ?
  AND status != 'revoked'
ORDER BY id DESC
LIMIT 1
`

type GetLatestCredentialParams struct {
	ProviderID string
	Kind       string
}

// The most recent credential that has not been revoked, whatever its status.
//
// GetLiveCredential deliberately excludes 'invalid' and 'expired', because those
// must not be USED. But they must still be re-checkable: a key rejected because
// of a provider-side hiccup would otherwise be condemned forever, recoverable
// only by re-submitting the secret. Revoked is the one terminal state  -  that one
// the operator chose.
func (q *Queries) GetLatestCredential(ctx context.Context, arg GetLatestCredentialParams) (ProviderCredential, error) {
	row := q.db.QueryRowContext(ctx, getLatestCredential, arg.ProviderID, arg.Kind)
	var i ProviderCredential
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Kind,
		&i.Ciphertext,
		&i.Nonce,
		&i.KeyRef,
		&i.Cipher,
		&i.Hint,
		&i.AccountEmail,
		&i.Status,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.ExpiryIsEstimate,
		&i.LastVerifiedAt,
		&i.LastVerifyError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLiveCredential = `-- name: GetLiveCredential :one

SELECT id, provider_id, kind, ciphertext, nonce, key_ref, cipher,
       hint, account_email, status, issued_at, expires_at, expiry_is_estimate,
       last_verified_at, last_verify_error, created_at, updated_at
FROM provider_credentials
WHERE provider_id = ?
  AND kind = ?
  AND status IN ('active', 'unverified')
`

type GetLiveCredentialParams struct {
	ProviderID string
	Kind       string
}

// "Live" means the credential occupies the one slot per (provider, kind) that
// the partial unique index permits: in use, or sealed and awaiting its first
// verification. domain.CredentialStatus.Live() must agree with this predicate.
func (q *Queries) GetLiveCredential(ctx context.Context, arg GetLiveCredentialParams) (ProviderCredential, error) {
	row := q.db.QueryRowContext(ctx, getLiveCredential, arg.ProviderID, arg.Kind)
	var i ProviderCredential
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Kind,
		&i.Ciphertext,
		&i.Nonce,
		&i.KeyRef,
		&i.Cipher,
		&i.Hint,
		&i.AccountEmail,
		&i.Status,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.ExpiryIsEstimate,
		&i.LastVerifiedAt,
		&i.LastVerifyError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCredential = `-- name: InsertCredential :one
INSERT INTO provider_credentials (
    provider_id, kind, ciphertext, nonce, key_ref, cipher,
    hint, account_email, status, issued_at, expires_at, expiry_is_estimate,
    last_verified_at, last_verify_error, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertCredentialParams struct {
	ProviderID       string
	Kind             string
	Ciphertext       []byte
	Nonce            []byte
	KeyRef           string
	Cipher           string
	Hint             string
	AccountEmail     string
	Status           string
	IssuedAt         sql.NullString
	ExpiresAt        sql.NullString
	ExpiryIsEstimate int64
	LastVerifiedAt   sql.NullString
	LastVerifyError  string
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) InsertCredential(ctx context.Context, arg InsertCredentialParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertCredential,
		arg.ProviderID,
		arg.Kind,
		arg.Ciphertext,
		arg.Nonce,
		arg.KeyRef,
		arg.Cipher,
		arg.Hint,
		arg.AccountEmail,
		arg.Status,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.ExpiryIsEstimate,
		arg.LastVerifiedAt,
		arg.LastVerifyError,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listLiveCredentials = `-- name: ListLiveCredentials :many
SELECT id, provider_id, kind, ciphertext, nonce, key_ref, cipher,
       hint, account_email, status, issued_at, expires_at, expiry_is_estimate,
       last_verified_at, last_verify_error, created_at, updated_at
FROM provider_credentials
WHERE status IN ('active', 'unverified')
ORDER BY provider_id, kind
`

func (q *Queries) ListLiveCredentials(ctx context.Context) ([]ProviderCredential, error) {
	rows, err := q.db.QueryContext(ctx, listLiveCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderCredential{}
	for rows.Next() {
		var i ProviderCredential
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Kind,
			&i.Ciphertext,
			&i.Nonce,
			&i.KeyRef,
			&i.Cipher,
			&i.Hint,
			&i.AccountEmail,
			&i.Status,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.ExpiryIsEstimate,
			&i.LastVerifiedAt,
			&i.LastVerifyError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retireCredentials = `-- name: RetireCredentials :exec
UPDATE provider_credentials
SET status     = ?,
    updated_at = ?
WHERE provider_id = ?
  AND kind = ?
  AND status IN ('active', 'unverified')
`

type RetireCredentialsParams struct {
	Status     string
	UpdatedAt  string
	ProviderID string
	Kind       string
}

// Frees the slot the partial unique index guards, so a replacement credential
// can be inserted. Superseded rows are kept, not deleted: what was tried is
// part of the record.
func (q *Queries) RetireCredentials(ctx context.Context, arg RetireCredentialsParams) error {
	_, err := q.db.ExecContext(ctx, retireCredentials,
		arg.Status,
		arg.UpdatedAt,
		arg.ProviderID,
		arg.Kind,
	)
	return err
}

const updateCredentialMeta = `-- name: UpdateCredentialMeta :execrows
UPDATE provider_credentials
SET hint               = ?,
    account_email      = ?,
    issued_at          = ?,
    expires_at         = ?,
    expiry_is_estimate = ?,
    last_verified_at   = ?,
    updated_at         = ?
WHERE id = ?
  AND status != 'revoked'
`

type UpdateCredentialMetaParams struct {
	Hint             string
	AccountEmail     string
	IssuedAt         sql.NullString
	ExpiresAt        sql.NullString
	ExpiryIsEstimate int64
	LastVerifiedAt   sql.NullString
	UpdatedAt        string
	ID               int64
}

// Writes every field, and carries the same guard as the status update.
//
// MERGING is the caller's job, not this query's: which fields a driver is
// entitled to overwrite is a business rule, and it lives in ProviderService
// where the stored metadata is already in hand. Doing it in SQL would also have
// meant COALESCE/NULLIF, which sqlc's SQLite parser cannot name parameters
// inside.
func (q *Queries) UpdateCredentialMeta(ctx context.Context, arg UpdateCredentialMetaParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCredentialMeta,
		arg.Hint,
		arg.AccountEmail,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.ExpiryIsEstimate,
		arg.LastVerifiedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCredentialStatus = `-- name: UpdateCredentialStatus :execrows
UPDATE provider_credentials
SET status            = ?,
    last_verify_error = ?,
    updated_at        = ?
WHERE id = ?
  AND status != 'revoked'
`

type UpdateCredentialStatusParams struct {
	Status          string
	LastVerifyError string
	UpdatedAt       string
	ID              int64
}

// Guarded, and reporting rows affected, because verification deliberately runs
// outside a transaction: the row can be revoked by a DELETE or superseded while
// the provider is being called, and a late verdict writing 'active' back would
// resurrect it. Zero rows means "superseded", a normal outcome rather than an
// error.
//
// The guard is `!= 'revoked'` rather than a liveness test, so an 'invalid'
// credential can still be re-verified back to 'active'. Revoked is the only
// terminal state, because it is the only one the operator chose.
func (q *Queries) UpdateCredentialStatus(ctx context.Context, arg UpdateCredentialStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCredentialStatus,
		arg.Status,
		arg.LastVerifyError,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
