// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: providers.sql

package sqlite

import (
	"context"
)

const getProvider = `-- name: GetProvider :one
SELECT id, display_name, kind, enabled, config, created_at, updated_at
FROM providers
WHERE id = ?
`

func (q *Queries) GetProvider(ctx context.Context, id string) (Provider, error) {
	row := q.db.QueryRowContext(ctx, getProvider, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Kind,
		&i.Enabled,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProviders = `-- name: ListProviders :many
SELECT id, display_name, kind, enabled, config, created_at, updated_at
FROM providers
ORDER BY id
`

func (q *Queries) ListProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.QueryContext(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Kind,
			&i.Enabled,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProviderEnabled = `-- name: SetProviderEnabled :exec
UPDATE providers
SET enabled    = ?,
    updated_at = ?
WHERE id = ?
`

type SetProviderEnabledParams struct {
	Enabled   int64
	UpdatedAt string
	ID        string
}

func (q *Queries) SetProviderEnabled(ctx context.Context, arg SetProviderEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setProviderEnabled, arg.Enabled, arg.UpdatedAt, arg.ID)
	return err
}

const upsertProvider = `-- name: UpsertProvider :exec
INSERT INTO providers (id, display_name, kind, enabled, config, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE
SET display_name = excluded.display_name,
    kind         = excluded.kind,
    updated_at   = excluded.updated_at
`

type UpsertProviderParams struct {
	ID          string
	DisplayName string
	Kind        string
	Enabled     int64
	Config      string
	CreatedAt   string
	UpdatedAt   string
}

// Seeding is idempotent: the registry calls this at every boot. display_name and
// kind come from the driver and are refreshed; enabled and config are NOT
// overwritten. Seed supplies no config, so refreshing it would reset the column
// to '{}' on every restart  -  which nothing notices today only because nothing
// writes it yet.
func (q *Queries) UpsertProvider(ctx context.Context, arg UpsertProviderParams) error {
	_, err := q.db.ExecContext(ctx, upsertProvider,
		arg.ID,
		arg.DisplayName,
		arg.Kind,
		arg.Enabled,
		arg.Config,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
