root: agentic
stacks:
  - github.com/pedromvgomes/agentic-toolkit.git/stacks/default.yaml
  - github.com/pedromvgomes/agentic-toolkit.git/stacks/plannotator.yaml
  - github.com/pedromvgomes/agentic-toolkit.git/stacks/serena.yaml
  - github.com/pedromvgomes/agentic-toolkit.git/stacks/rtk.yaml
  - ./agentic/stacks/chrome-devtools.yaml
memory:
  agent: claudecode
  root: .agents/memory
