// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login_sessions.sql

package sqlite

import (
	"context"
	"database/sql"
)

const createLoginSession = `-- name: CreateLoginSession :exec
INSERT INTO login_sessions (
    id, provider_id, state, auth_url, prompt, error_code, error_message,
    credential_id, child_pid, transcript, created_at, updated_at, expires_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateLoginSessionParams struct {
	ID           string
	ProviderID   string
	State        string
	AuthUrl      string
	Prompt       string
	ErrorCode    string
	ErrorMessage string
	CredentialID sql.NullInt64
	ChildPid     sql.NullInt64
	Transcript   string
	CreatedAt    string
	UpdatedAt    string
	ExpiresAt    string
}

func (q *Queries) CreateLoginSession(ctx context.Context, arg CreateLoginSessionParams) error {
	_, err := q.db.ExecContext(ctx, createLoginSession,
		arg.ID,
		arg.ProviderID,
		arg.State,
		arg.AuthUrl,
		arg.Prompt,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.CredentialID,
		arg.ChildPid,
		arg.Transcript,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ExpiresAt,
	)
	return err
}

const failAllNonTerminalLoginSessions = `-- name: FailAllNonTerminalLoginSessions :execrows
UPDATE login_sessions
SET state         = 'failed',
    error_code    = 'daemon_restarted',
    error_message = ?,
    updated_at    = ?
WHERE state NOT IN ('succeeded', 'failed', 'timed_out', 'canceled')
`

type FailAllNonTerminalLoginSessionsParams struct {
	ErrorMessage string
	UpdatedAt    string
}

// Runs at daemon startup. A session's PTY and child process do not survive a
// restart, so any row still mid-flight is describing something that no longer
// exists.
func (q *Queries) FailAllNonTerminalLoginSessions(ctx context.Context, arg FailAllNonTerminalLoginSessionsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failAllNonTerminalLoginSessions, arg.ErrorMessage, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLoginSession = `-- name: GetLoginSession :one
SELECT id, provider_id, state, auth_url, prompt, error_code, error_message,
       credential_id, child_pid, transcript, created_at, updated_at, expires_at
FROM login_sessions
WHERE id = ?
`

func (q *Queries) GetLoginSession(ctx context.Context, id string) (LoginSession, error) {
	row := q.db.QueryRowContext(ctx, getLoginSession, id)
	var i LoginSession
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.State,
		&i.AuthUrl,
		&i.Prompt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CredentialID,
		&i.ChildPid,
		&i.Transcript,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateLoginSession = `-- name: UpdateLoginSession :exec
UPDATE login_sessions
SET state         = ?,
    auth_url      = ?,
    prompt        = ?,
    error_code    = ?,
    error_message = ?,
    credential_id = ?,
    child_pid     = ?,
    transcript    = ?,
    updated_at    = ?,
    expires_at    = ?
WHERE id = ?
`

type UpdateLoginSessionParams struct {
	State        string
	AuthUrl      string
	Prompt       string
	ErrorCode    string
	ErrorMessage string
	CredentialID sql.NullInt64
	ChildPid     sql.NullInt64
	Transcript   string
	UpdatedAt    string
	ExpiresAt    string
	ID           string
}

func (q *Queries) UpdateLoginSession(ctx context.Context, arg UpdateLoginSessionParams) error {
	_, err := q.db.ExecContext(ctx, updateLoginSession,
		arg.State,
		arg.AuthUrl,
		arg.Prompt,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.CredentialID,
		arg.ChildPid,
		arg.Transcript,
		arg.UpdatedAt,
		arg.ExpiresAt,
		arg.ID,
	)
	return err
}
