// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

import (
	"database/sql"
)

type LoginSession struct {
	ID           string
	ProviderID   string
	State        string
	AuthUrl      string
	Prompt       string
	ErrorCode    string
	ErrorMessage string
	CredentialID sql.NullInt64
	ChildPid     sql.NullInt64
	Transcript   string
	CreatedAt    string
	UpdatedAt    string
	ExpiresAt    string
}

type Provider struct {
	ID          string
	DisplayName string
	Kind        string
	Enabled     int64
	Config      string
	CreatedAt   string
	UpdatedAt   string
}

type ProviderCredential struct {
	ID               int64
	ProviderID       string
	Kind             string
	Ciphertext       []byte
	Nonce            []byte
	KeyRef           string
	Cipher           string
	Hint             string
	AccountEmail     string
	Status           string
	IssuedAt         sql.NullString
	ExpiresAt        sql.NullString
	ExpiryIsEstimate int64
	LastVerifiedAt   sql.NullString
	LastVerifyError  string
	CreatedAt        string
	UpdatedAt        string
}

type Setting struct {
	Key       string
	Value     string
	UpdatedAt string
}

type UpdateState struct {
	ID           int64
	Status       string
	FromVersion  string
	ToVersion    string
	BootAttempts int64
	StartedAt    sql.NullString
	UpdatedAt    string
}
