// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_state.sql

package sqlite

import (
	"context"
	"database/sql"
)

const getUpdateState = `-- name: GetUpdateState :one

SELECT status, from_version, to_version, boot_attempts, started_at, updated_at
FROM update_state
WHERE id = 1
`

type GetUpdateStateRow struct {
	Status       string
	FromVersion  string
	ToVersion    string
	BootAttempts int64
	StartedAt    sql.NullString
	UpdatedAt    string
}

// A single row, id = 1, enforced by a CHECK. It exists to survive the process
// restart that completes an update, which is why it is not in memory.
func (q *Queries) GetUpdateState(ctx context.Context) (GetUpdateStateRow, error) {
	row := q.db.QueryRowContext(ctx, getUpdateState)
	var i GetUpdateStateRow
	err := row.Scan(
		&i.Status,
		&i.FromVersion,
		&i.ToVersion,
		&i.BootAttempts,
		&i.StartedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementBootAttempts = `-- name: IncrementBootAttempts :one
UPDATE update_state
SET boot_attempts = boot_attempts + 1,
    updated_at    = ?
WHERE id = 1
RETURNING status, from_version, to_version, boot_attempts, started_at, updated_at
`

type IncrementBootAttemptsRow struct {
	Status       string
	FromVersion  string
	ToVersion    string
	BootAttempts int64
	StartedAt    sql.NullString
	UpdatedAt    string
}

// One statement rather than a read-modify-write: this runs on every boot of a
// pending update, which is exactly when the process is most likely to die
// partway through.
func (q *Queries) IncrementBootAttempts(ctx context.Context, updatedAt string) (IncrementBootAttemptsRow, error) {
	row := q.db.QueryRowContext(ctx, incrementBootAttempts, updatedAt)
	var i IncrementBootAttemptsRow
	err := row.Scan(
		&i.Status,
		&i.FromVersion,
		&i.ToVersion,
		&i.BootAttempts,
		&i.StartedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const putUpdateState = `-- name: PutUpdateState :exec
UPDATE update_state
SET status        = ?,
    from_version  = ?,
    to_version    = ?,
    boot_attempts = ?,
    started_at    = ?,
    updated_at    = ?
WHERE id = 1
`

type PutUpdateStateParams struct {
	Status       string
	FromVersion  string
	ToVersion    string
	BootAttempts int64
	StartedAt    sql.NullString
	UpdatedAt    string
}

func (q *Queries) PutUpdateState(ctx context.Context, arg PutUpdateStateParams) error {
	_, err := q.db.ExecContext(ctx, putUpdateState,
		arg.Status,
		arg.FromVersion,
		arg.ToVersion,
		arg.BootAttempts,
		arg.StartedAt,
		arg.UpdatedAt,
	)
	return err
}
